export const GET_PASSENGERS_LIST_SUCCESS = "GET_PASSENGERS_LIST_SUCCESS"

export const REMOVE_PASSENGER_SUCCESS = "REMOVE_PASSENGER_SUCCESS"

export const ADD_PASSENGER_SUCCESS = "ADD_PASSENGER_SUCCESS"

export const VIEW_DETAILS_SUCCESS = "VIEW_DETAILS_SUCCESS"

export const BOOK_TICKET_SUCCESS = "BOOK_TICKET_SUCCESS"