export const GET_PASSENGERS_LIST_BEGINS = "GET_PASSENGERS_LIST_BEGINS"
export const GET_PASSENGERS_LIST_SUCCESS = "GET_PASSENGERS_LIST_SUCCESS"
export const GET_PASSENGERS_LIST_FAILURE = "GET_PASSENGERS_LIST_FAILURE"